version: '3.7'

services:
  nestjs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/nestjs-backend/src
    ports:
      - 3000:3000
    env_file:
      - ./src/config/envs/.development.env

  postgres-database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: nestjs-backend
      POSTGRES_USER: taeyoon
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
