POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=test-file-upload

--test-file-upload
Content-Disposition: form-data; name="file"; filename="test.txt"

# 테스트 텍스트 파일 지정
# 실제 파일의 상대 경로 또는 절대 경로를 지정해 파일을 지정할 수 있다.
< test.txt
--test-file-upload--